// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxuggmzqkmwfbsdqmrgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4dWdnbXpxa213ZmJzZHFtcmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzgxMDQsImV4cCI6MjA1Njg1NDEwNH0.A7zNJih17wxt989phG89SGi-B5OW0cC_RW1lA2czksw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);